[package]
name = "vela-peer-service"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
base64.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
vela-core = { path = "../vela-core" }
vela-crypto = { path = "../vela-crypto" }
vela-diagnostic = { path = "../vela-diagnostic" }
vela-ip = { path = "../vela-ip" }
vela-proto = { path = "../vela-proto" }
vela-tun = { path = "../vela-tun" }
rustls.workspace = true
