[package]
name = "vela-tun"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bytes.workspace = true
futures-util.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true
vela-core = { path = "../vela-core" }
vela-proto = { path = "../vela-proto" }

[dev-dependencies]
blake3.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
rtnetlink.workspace = true

[target.'cfg(any(target_os = "macos", target_os = "windows"))'.dependencies]
route_manager.workspace = true
tun-rs.workspace = true
