[package]
name = "vela-tun"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bytes.workspace = true
futures-util.workspace = true
libc = "0.2"
rtnetlink.workspace = true
thiserror.workspace = true
tokio.workspace = true
vela-core = { path = "../vela-core" }
vela-proto = { path = "../vela-proto" }
