[package]
name = "vela-stack"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bytes.workspace = true
smoltcp.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
vela-core = { path = "../vela-core" }

[dev-dependencies]
vela-crypto = { path = "../vela-crypto" }
vela-proto = { path = "../vela-proto" }
